//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import Quick
import Nimble

class ___VARIABLE_sceneName___WorkerTests: QuickSpec {
    
    // MARK: Subject under test
    
    var sut: ___VARIABLE_sceneName___Worker!

    override func spec() {
        describe("The ___VARIABLE_sceneName___ Worker") {

            beforeEach {
                self.sut = ___VARIABLE_sceneName___Worker()
            }

            describe("on .....") {
                it("should .....") {

                }
            }
        }
    }
}
