//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ___VARIABLE_sceneName___PresenterInterface {
    func present___VARIABLE_resourceName___(response: ___VARIABLE_sceneName___Models.Fetch___VARIABLE_resourceName___.Response)
}

class ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresenterInterface {
    
    // MARK: - Properties
    
    weak var viewController: ___VARIABLE_sceneName___DisplayInterface?
    
    // MARK: - ___VARIABLE_sceneName___PresenterInterface
    
    func present___VARIABLE_resourceName___(response: ___VARIABLE_sceneName___Models.Fetch___VARIABLE_resourceName___.Response) {
        let viewModel = ___VARIABLE_sceneName___Models.Fetch___VARIABLE_resourceName___.ViewModel()
        viewController?.display___VARIABLE_resourceName___(viewModel: viewModel)
    }
}
