//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol ___VARIABLE_sceneName___InteractorInterface {
    func fetch___VARIABLE_resourceName___(request: ___VARIABLE_sceneName___Models.Fetch___VARIABLE_resourceName___.Request)
}

protocol ___VARIABLE_sceneName___DataStore {
    
}

class ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___InteractorInterface, ___VARIABLE_sceneName___DataStore {
   
    // MARK: - Properties
    
    var presenter: ___VARIABLE_sceneName___PresenterInterface?
    var worker: ___VARIABLE_sceneName___WorkerInterface = ___VARIABLE_sceneName___Worker()
    
    // MARK: - ___VARIABLE_sceneName___InteractorInterface
    
    func fetch___VARIABLE_resourceName___(request: ___VARIABLE_sceneName___Models.Fetch___VARIABLE_resourceName___.Request) {
        
        // Perform network requests here and present afterwards
        
        let response = ___VARIABLE_sceneName___Models.Fetch___VARIABLE_resourceName___.Response()
        presenter?.present___VARIABLE_resourceName___(response: response)
    }
}
