//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ___PROJECTNAMEASIDENTIFIER___
import XCTest

class ___VARIABLE_sceneName___ViewControllerTests: XCTestCase {
    
    // MARK: Subject under test
    
    var sut: ___VARIABLE_sceneName___ViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setup___VARIABLE_sceneName___ViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setup___VARIABLE_sceneName___ViewController() {
        
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: X, bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: String(describing: ___VARIABLE_sceneName___ViewController.self)) as! ___VARIABLE_sceneName___ViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class ___VARIABLE_sceneName___InteractorSpy: ___VARIABLE_sceneName___InteractorInterface {

    }
    
    // MARK: Tests
    
    func testShouldDoSomethingWhenViewIsLoaded() {
        
        // Given
        
        // When
        
        // Then
    }
    
    func testDisplaySomething() {
        
        // Given
        
        // When
        loadView()
        
        // Then
    }
}
